### ISSUE TITLE
Create Detail View Page

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#16]
**Story:** After finding a potentially interesting component, I want to check its detail description to get to know more. 

**Implementation**
Provide these functions on detail view: 
* Data on the component
* Go back to data explorer view
* Download the data on this item (→ Ticket for download?)

**Assumption:** People would usually come here from the data explorer page (#17)

**Criteria**

* Push view change to browser history back stack

### Interface Sketch

![image](https://user-images.githubusercontent.com/3416487/124460958-566dd600-dd90-11eb-881b-68d7937e028c.png)

**Comment by jdittrich** [comment]
details, as described ion #23 might be: 

> metadata completeness (=extent to which the specification has been complied; also indicating the completeness of documentation)
data source
name
version + timestamp
repo URL
image
licensor, owner, organisation
license
functional description
number of contributors
list & number of self-designed parts
URLs to source & export files (including BoM and manuals)
production metadata (yet to be processed from here)

**Comment by botoxparty** [comment]
So here is a sample of the data from the current test instance that we are using in the frontend:

https://jsonblob.com/d7f4a7b3-f2a6-11eb-b83e-2b09a76bcb03

I am unclear about the licensor/owner/organisation field, and data source field.

@jdittrich I think you were waiting on finalised data to be able to create a final mockup for the detail page. It may be worth catching up together with @moedn to discuss the data set and how to present it.

**Comment by moedn** [comment]
Jo, can I help somehow with licensor/owner/organisation and data source fields?

Meeting may make sense; I'll send you a mail

**Comment by botoxparty** [comment]
Discussion moved to https://github.com/wmde/LOSH-Frontend/issues/67
