### ISSUE TITLE
Choose UI framework

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#19]

**Comment by M01M01** [comment]
UI  frameworks that support Vue.js 3:

SuperBVue(uses bootstrap 5)
https://superbvue.netlify.app/
https://github.com/superbvue/SuperBVue

BalmUI
https://next-material.balmjs.com/
https://github.com/balmjs/balm-ui

Element 3
https://element3-ui.com/
https://github.com/hug-sun/element3

Vuestic UI
https://vuestic.dev/
https://github.com/epicmaxco/vuestic-ui

Qui Max
https://github.com/Qvant-lab/qui-max

**Comment by botoxparty** [comment]
Unfortunately at this point in time Bootstrap is not an ideal candidate as there is no mature library that exists for Vue3/Bootstrap5 and we would have to import the full bootstrap lib and use the standard HTML/css/JS approach for implementation. It is preferred to use a Vue component based library.

We have filtered the options for UI kits down to the following candidates. Will go through these options with Jan to see what he feels would be most appropriate to execute his design.

**Ant Design Vue**
https://antdv.com/docs/vue/introduce/
https://github.com/vueComponent/ant-design-vue
- Data table has filtering and sorting
- Cards
- Used in over 19k projects
- Developed by ant design (Alibaba) 
- Figma UI kit - https://antforfigma.com/

**PrimeVue**
https://www.primefaces.org/primevue/showcase/
https://github.com/primefaces/primevue
- Used in over 2.6k projects
- Figma UI Kit - https://www.figma.com/community/file/890589747170608208

**Quasar**
https://quasar.dev/start/pick-quasar-flavour
https://github.com/quasarframework/quasar
- Used in over 14k projects
- Table supports a global filter, not column based filtering
- Can use any Material design UI kit https://www.figma.com/@materialdesign

**Comment by jdittrich** [comment]
Ant and Prime seem to have the best table components.

**Comment by jdittrich** [comment]
We said we would possibly use vuepress or vitepress for generating the whole site, right? Are the component libs drop-in for this or do we need to check for vite/vuepress compatibility, too?

**Comment by botoxparty** [comment]
The component libs are drop-ins and will work with any type of Vue configuration.

**Comment by botoxparty** [comment]
Ant Design has been selected as the UI framework
