### ISSUE TITLE
Evaluate querying options for Filtering

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#20]
[Cirrus Search extension](https://www.mediawiki.org/wiki/Extension:CirrusSearch)

**Comment by jdittrich** [comment]
I think the normal cirrus search extension does not cover how to search for Wikidata Items. It might, however just use a serialized version of the data and simply text-search over it?

**Comment by addshore** [comment]
So there are some advanced features of search for wikibase
These are documented at https://www.mediawiki.org/wiki/Help:Extension:WikibaseCirrusSearch

These enable for example., looking for a statement match https://losh.ose-germany.de/index.php?search=haswbstatement%3AP71%3Dhttps%3A%2F%2Fgithub.com%2FOPEN-NEXT%2FOKH-LOSH%2Fraw%2Fmaster%2FOKH-LOSH.ttl%23Module&title=Special%3ASearch&profile=default&fulltext=1

And that can also be done with free text https://losh.ose-germany.de/index.php?search=table+haswbstatement%3AP71%3Dhttps%3A%2F%2Fgithub.com%2FOPEN-NEXT%2FOKH-LOSH%2Fraw%2Fmaster%2FOKH-LOSH.ttl%23Module&title=Special%3ASearch&profile=default&fulltext=1

What are the search cases we are trying to implement for here?

**Comment by ckawohl-wmde** [comment]
It seems that sorting is out of scope - it would require writing a separate module that would create a "hack" using the search capabilities of CirrusSearch, in short this wouldn't be a scalable and reliable option as sorting.

**Comment by ckawohl-wmde** [comment]
This is a duplicate - implementation of filtering is tackled in #91
