### ISSUE TITLE
Mock backend API

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#21]
To enable working on the frontend independently from the backend, it makes sense to mock the data returned from the backend. Thus, work can commence in a realistic setting _and_ there would be a clearly defined channel of exchange between frontend/backend.

**Comment by botoxparty** [comment]
Some sample data that can be used as a base to generate mock data can be found here:

https://github.com/OPEN-NEXT/OKH-LOSH/blob/master/sample_data/

**Comment by botoxparty** [comment]
TODO: Evaluate existing data in https://cdata.oho.wiki/

**Comment by botoxparty** [comment]
Test instance has been setup successfully and is used as mock backend
