### ISSUE TITLE
Initialise vite project

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#22]

**Comment by botoxparty** [comment]
Initially, it was decided to use [Vitepress](https://github.com/vuejs/vitepress) however it is still marked as WIP and not recommended for use in real projects.

So the next step was to use Vuepress (which Vitepress was based on) however the stable release uses Vue 2 and not Vue 3. The option is available to use the beta version of Vuepress 2 which includes Vue 3 however at this point my thoughts are to abandon the Vue ecosystem for this project as it's currently in flux and support between UI libraries, developer tooling, Typescript is not as mature as something like React.

Therefore will be switching the project to Gatsby at this point to continue development futher.

I understand also that WMDE would prefer to have all projects from now using Vue however based on the short-term support we are providing on this and not knowing who will maintain it after (will it ever get upgraded from the beta?) I believe the safest option is to use a stable version of Gatsby.
