### ISSUE TITLE
determine schema of data presented to the user

### ISSUE THREAD

**Issue by jdittrich** [wmde/LOSH-Frontend#23]
Story: ---

For presenting the data, we need to know what fields exist and what types they have so we can present them to the user. 

e.g. 
`
License<String>,
Cost<Float>,
…
`
or similar

This is relevant for #21 (Mock backend API), #17 (Data explorer page), #16 (Detail View), #3 (Filtering)

**Comment by botoxparty** [comment]
Looking at the live instance, I discovered the following properties:

```
Identifier (URL)
Name
Bill of materials (BOM)
SPDX license identifier
Version
License
Documentation readiness level
Technology readiness level
Has part
Number of contributors
File URL
```

Based on the list from the specifications, I would say it is safe to assume that the following will be required for the data table:

```
name
version + timestamp
repo URL
licensor, owner, organisation
license
URLs to source & export files (including BoM and manuals)
```

The rest below are either only required for the detail page or I don't really know if they are going to have this data ready. We can start building the data table with at least the basics that we know about and start adding columns from there.

```
data source
image
functional description
number of contributors
list & number of self-designed parts
production metadata (yet to be processed from here)
metadata completeness (=extent to which the specification has been complied; also indicating the completeness of documentation)
```

**Comment by botoxparty** [comment]
@jdittrich I found a sample of the mock data that will be entered into the wikibase instance:

https://github.com/OPEN-NEXT/OKH-LOSH/blob/master/sample_data/okh-OHLOOM.toml#L1-L23

```
okhv = "2.0"
name = "OHLOOM"
repo = "https://gitlab.com/OSEGermany/ohloom"
version = "0.10.0"
release = "https://gitlab.com/OSEGermany/ohloom/-/tags/ohloom-0.10.0"
license = "CC-BY-SA-4.0"
licensor = "Jens Meisner"
organisation = "OSE Germany e.V."
readme = "README.md"
image = "/Documentation/User_Guide/User_Guide.jpg"
documentation-language = "en-GB"
technology-readiness-level = "OTLR-5"
documentation-readiness-level = "ODLR-5"
function = "The Open Hardware Loom is a simple, hand-operated weaving loom made of wood, screws and 3D printed plastic pieces for the most part. It is simple to make and operate."
cpc-patent-class = "D03D 35/00"
tsdc = "MEC"
bom = "sBoM.csv"
manufacturing-instructions = "/Documentation/Assembly_Guide/AssemblyGuide.md"
user-manual = "/Documentation/User_Guide/UserGuide.md"
fabric-width-dim = "mm"
fabric-width = 400
outer-dimension-dim = "mm"
outer-dimension = "cube(size = [400,350,150]"
```

**Comment by jdittrich** [comment]
So this is probably the manifest file that defines what is in a hardware definition
