### ISSUE TITLE
Implement Filtering (Frontend)

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#3]
**Story:** As a maker, I want to find open source hardware components that match my needs.

**Assumption**: There is a database providing information (see #23) about open source hardware items. This information is presented to the user and needs to be searched/filtered. 

**Criteria:**
These are very much like one is used to in faceted search, e.g. online shopping for shoes: There are ranges (size, price) and criteria (color, brands)

* Multiple filtering criteria should be allowed
* Across data types (columns in a table) the data is filtered by AND (If I select "price < 10€ and manufactured =  China, I get all items that are both cheaper than 10€ and manufactured in China) 
* Optional: If there are multiple possible values selectable values within a type they get connected by OR (If I select manufactured in = [China, Germany], I get items that are either manufactured in China or manufactured in Germany)

**Interface Sketch**
(not final, we might also want the filtering to be integrated in the table or the like)

![image](https://user-images.githubusercontent.com/3416487/124460342-8bc5f400-dd8f-11eb-9b2a-0907ce7533d9.png)

**Comment by jdittrich** [comment]
I wonder how search and filtering would (not) work together.  If we have a search, would it first search and then filter down the results according to the filter?

**Comment by jdittrich** [comment]
Filtering and search will be done by the backend.

**Comment by botoxparty** [comment]
Based on the [findings from the evaluation #20](https://github.com/wmde/LOSH-Frontend/issues/20#issuecomment-952623047)

The implementation of filtering and sorting is currently limited until the mappings that in Elasticsearch created by  CirrusSearch have been updated to support the filtering and sorting requirements.

**Comment by ckawohl-wmde** [comment]
Closing this issue since the implementation will be tackled in #91
