### ISSUE TITLE
Theming fonts and colors

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#30]

**Comment by jdittrich** [comment]
I took the colors from https://opennext.eu and introduced two additional colors, as the original ones don't have enough contrast to white/black fonts. 

* Accent-blue-light: 97C5F1
* blue-text: 5087BC

The existing ones are: 
* Yellow: fff963
* Darkgray: 656471
* light gray: ededed

**Comment by jdittrich** [comment]
Fonts: 
* Source Sans Pro
* Source Code Pro
