### ISSUE TITLE
Implement theming and colors

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#33]

**Comment by botoxparty** [comment]
Hey @jdittrich

Please go through the current implementation and create any follow up tickets regarding styling/theming issues that you encounter.

The deployed URL can be found here:

https://zen-stonebraker-a93ddf.netlify.app/

**Comment by jdittrich** [comment]
Seems to be fine in general, for smaller fixes I open(ed) tickets. Push to done.
