### ISSUE TITLE
Implement Search (Frontend)

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#4]
**Story**: As a maker I want to quickly find open source hardware of a particular company or with a particular feature that might be mentioned in description texts

**Note**: Search and filtering will be handled by the backend, we would just need to get user input, provide the data and display the results

**Interface sketch**: 
![image](https://user-images.githubusercontent.com/3416487/124561271-fe8da880-de3d-11eb-90e2-7e97c63a2e4e.png)

**Comment by botoxparty** [comment]
A search endpoint has been implemented in the server package.

- Finds the item IDs using Elasticsearch
- Populates the results using MW-API

This could be optimised further by implementing the changes that were discovered in [Evaluate querying options for Sorting/Filtering #20](https://github.com/wmde/LOSH-Frontend/issues/20)

By changing the documents that are mapped in Elastic be the same as the result of a MW-API response, the amount of requests it takes to complete a search could be halved.
