### ISSUE TITLE
UX: Animations too slow

### ISSUE THREAD

**Issue by jdittrich** [wmde/LOSH-Frontend#41]
**Describe the bug**
The animations of the underlining of the links and the and the unfolding of the menus (action menus explore, hamburger menu mobile view) are slow.

**To Reproduce**

1. Hover a link in the site menu

or 

1. Click on one of the action menus on "Explore data"

…it takes a moment to see that your action had an effect

The animation curve is probably something like
![image](https://user-images.githubusercontent.com/3416487/126460882-86d1c035-bf48-494d-93a1-fbeac9c55021.png)

or even 

![image](https://user-images.githubusercontent.com/3416487/126460979-9fbb63f6-9e37-4c2d-918b-0109777aefe7.png)

**Expected behavior**
The actions of the users should have an feel-able, immediate effect. 

The animation curve should be like

![image](https://user-images.githubusercontent.com/3416487/126461156-9ff5a5fc-96e5-4b10-9a04-72587edcc33c.png)
or
![image](https://user-images.githubusercontent.com/3416487/126461238-c7105fa5-948f-45d4-be69-36c2f5390e1a.png)

**Comment by botoxparty** [comment]
Indeed, the current animation curve looks something like this:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/24580068/126905747-da809da4-c69b-4d96-aab2-b535a8b4b5d6.png">

I have updated the ease-in-out curve to look like this:

<img width="272" alt="image" src="https://user-images.githubusercontent.com/24580068/126905948-c75e0fd2-d099-43b8-a2fb-6f98f47a906a.png">

**Comment by botoxparty** [comment]
@jdittrich Can you please review this?

**Comment by jdittrich** [comment]
Generally fine, can be cranked up even a bit steeper at the start.

**Comment by botoxparty** [comment]
Should now look like this:

![image](https://user-images.githubusercontent.com/24580068/136653622-f6cfb9ec-5d43-4071-ad95-881fdfb3ce6b.png)

**Comment by jdittrich** [comment]
excellent!
