### ISSUE TITLE
UX: Restyle Buttons

### ISSUE THREAD

**Issue by jdittrich** [wmde/LOSH-Frontend#48]
Maybe you already implemented all this. I just want to make sure that the states of our buttons work fine. The [specs are in figma, too](https://www.figma.com/file/pHfpLoKw9ssoSWZ4b5xJui/LOSH-Frontend-App-1?node-id=170%3A4150).

1. Primary: 
normal; active/hover; disabled
![three buttons](https://user-images.githubusercontent.com/3416487/126512016-51d407b9-d139-42e4-93aa-f7e6f94f0eb4.png)

2. Secondary
normal; active/hover; disabled
![three secondary buttons](https://user-images.githubusercontent.com/3416487/126512165-10580527-f3cc-4ee2-bcde-e55c9d82aa56.png)

**Comment by ckawohl-wmde** [comment]
@jdittrich has this been reviewed already? If so, please let me know so we can close this issue. Thanks :)

**Comment by jdittrich** [comment]
Lets close it; If there are problems I open a new ticket
