### ISSUE TITLE
Provide Favicon

### ISSUE THREAD

**Issue by botoxparty** [wmde/LOSH-Frontend#53]
Currently the default Gastby favicon appears.

**Comment by jdittrich** [comment]
I guess 
this: https://opennext.eu/wp-content/uploads/cropped-Icon2-02-32x32.png
that: https://opennext.eu/wp-content/uploads/cropped-Icon2-02-192x192.png
except we are asked to provide a custom one – trying to  avoid unsolicited logo designs, is usually a mess.

**Comment by botoxparty** [comment]
Favicon updated to those that were provided
