### ISSUE TITLE
H2 headlines do not define upper distance  

### ISSUE THREAD

**Issue by jdittrich** [wmde/LOSH-Frontend#59]
**Describe the bug**
Headlines in the main text area have few space above, making it easy to visually group them not with "their", that is, the following content, but with what comes before. Curiously, h2 does lack the top distance, while h3 has them. 

![image](https://user-images.githubusercontent.com/3416487/127319736-79582543-8ad7-4149-98ec-4a14ab573f61.png)

**Expected behavior**
* A margin-top of 1em (or an equivalent in the ant system) is usually helpful. 
* *except* the element is the `first-child:` element in a container (otherwise, different headlines lead to different distances from the outer container. 

![image](https://user-images.githubusercontent.com/3416487/127319802-c0c9cbcd-a98b-4a98-8fbe-219c0a18a14f.png)

related: #57

**Comment by botoxparty** [comment]
I have added a margin to all heading elements, only if they are not the first-child element.

Seems to work well.
