### ISSUE TITLE
Define infrastructure for deployment

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#6]

**Comment by botoxparty** [comment]
Will start with building and testing using Github Actions, and can modify the deploy stage at a later date when it's defined.

**Comment by botoxparty** [comment]
@moedn Do you happen to know where the static frontend files will be deployed when in production? The pipeline is currently setup to build and test in Github Actions.

Looking to start setting up the deploy stage.

**Comment by moedn** [comment]
Jepp, frontend will be hosted by [OSEG](https://ose-germany.de/), preferably via their [GitLab](https://gitlab.opensourceecology.de/) under the domain losh.ose-germany.de

**Comment by botoxparty** [comment]
@moedn Are you able to provide the contact details for the admin on the OSEG side so I can setup a meeting?

**Comment by moedn** [comment]
sure, I'll connect you via mail

**Comment by moedn** [comment]
@botoxparty any more details needed or has everything already been clarified between you and @aisbergg ? :)

**Comment by botoxparty** [comment]
Oh whoops sorry I got the tickets mixed up.

-

The repository is now structured as a monorepo with a client and server package. Both packages should be built according to the instructions in the README and deployed as node servers.
