### ISSUE TITLE
The font in the footer is 16px, should be 14px

### ISSUE THREAD

**Issue by jdittrich** [wmde/LOSH-Frontend#60]
**Describe the bug**
The font in the footer is 16px high, should be 14px

**To Reproduce**
Look at the bottom of the page! …no, a bit up again…
![image](https://user-images.githubusercontent.com/3416487/127450821-f138ff3e-ad30-4734-abf2-74ea11cfb7c9.png)

**Expected behavior**
![image](https://user-images.githubusercontent.com/3416487/127450976-008ece72-8fa6-4a75-9170-49f0a2f73e84.png)

`.ant-layout-footer span {…   font-size:14px…]`

(or any other CSS, as you like)

**Comment by botoxparty** [comment]
Should be fixed now :)

**Comment by jdittrich** [comment]
thanks!
