### ISSUE TITLE
Configurable Wikibase URL

### ISSUE THREAD

**Issue by aisbergg** [wmde/LOSH-Frontend#66]
**Is your feature request related to a problem? Please describe.**
Currently the [URL of the Wikibase instance is hardcoded to the production environment](https://github.com/wmde/LOSH-Frontend/blob/f14df8b25c094102335fb65e856f86c66d38fb11/src/context/query-context.tsx#L45). The URL of the production environment will change soon again. It would be nice, if the URL would be configurable. This would also allow to query other Wikibase instances in a staging instance for example.

**Describe the solution you'd like**
I like to be able to specify a `WIKIBASE_URL` environment variable at build time.

**Comment by botoxparty** [comment]
The URLs can now be provided as environment variables, see [Building documentation](https://github.com/wmde/LOSH-Frontend#building) :)
