### ISSUE TITLE
Feedback frontend detail page, order and display of properties

### ISSUE THREAD

**Issue by jdittrich** [wmde/LOSH-Frontend#67]
This is a review of the frontend detail page based on the [OHLOOM](https://zen-stonebraker-a93ddf.netlify.app/detail/Q438), which seems to be our most richly populated item. 

- [x] Put the functional description and the image to the top, I guess this is most relevant when calling up details, particularly because we can't put either in the table of results on the overview before. 
- [ ] For the order of the properties I would suggest Functional Description/Image/Related URLS/Data Source/Owner/License/Designed parts/[rest]
- [x] License property should be linked if URL 
![image](https://user-images.githubusercontent.com/3416487/136179756-82a10082-7e68-4fb4-b78f-effd8c07df2f.png), ideally it also would have a non-URL  name to the license (here, Creative Commons BY-SA-4.1) 
- [x] Let’s spell out TsDC to _Technology-specific Documentation Criteria (TsDC)_ 
- [ ] What does the timestamp mean? Last change? Creation of the instructions? Creation of the item in our database? If we know that we can get it a better label
- [x] I don't know if we parse that but it would be much nicer if we could put _cube(size = [400,350,150]_ as _length: 400mm, width: 350mm, height: 150mm_ (or however else these map to the dimensions; thus we would also get rid of the "cube", since the shape defined seems to be actually a _cuboid_ or just a (bounding) box)  If there is an accompanying sphere type, it could be rendered as diameter:1234mm 
-  [x] Could we move the buttons "Download Bundle" and "To… repo" next to each other? (Download bundle could in larger screen sizes next to To…repo; otherwise they would be vertically next to each other – or we just go with vertically next to each other for all screen sizes. 

<br><br>

![image](https://user-images.githubusercontent.com/3416487/136179004-a97662b2-2f5d-4b84-8b32-0f0ad131888f.png)

**Comment by moedn** [comment]
My comment on the detail page:

- download button works, super cool!
- would be nice to move essentials (`image`, `functional description`,`version`, `license`, `licensor`, `organisation`) to the top of the page
- substitute `Related URLs` with `Linked Files` or something like that ('related URLs' sounds like 'further information', but those should be essential files)
- split `licensor` from `organisation` → 2 distinct fields
- can we display the full designation of the CPC patent class in brackets behind the ID (and link it to CPC)? like that:\
  [D03D 35/00](https://worldwide.espacenet.com/patent/cpc-browser#!/CPC=D03D35/00) (Smallware looms, i.e. looms for weaving ribbons or other narrow fabrics)\
  `[D03D 35/00](https://worldwide.espacenet.com/patent/cpc-browser#!/CPC=D03D35/00) (Smallware looms, i.e. looms for weaving ribbons or other narrow fabrics)`

**Comment by botoxparty** [comment]
- The item that we preview on the detail page has a URL for its spdxLicense value, in the CSV you provided they are not URLs, is this an error in the data on this item? What can i expect?
- The designation of the CPC class can be retrieved using the Linked open EP data API, however in this example the patent class is identified as `D03D 35/00` whereas the API identifies it as `D03D35-00` ([see this API request](https://data.epo.org/linked-data/def/cpc/D03D35-00.json)), is it expected that all patent classes will follow a certain format that can be parsed to retrieve the full designation from the API?

**Comment by botoxparty** [comment]
For an example of the SPDX issue, you can see the raw values for the `spdxLicense` field are rendered in the table on the [test site](https://zen-stonebraker-a93ddf.netlify.app/): 

You can find the OHLOOM on page 6.

- - - - -

I have updated the design to match the latest mock in Figma, mixed with some of the feedback about the order of the items.

I am off this project for the next week, when I return i'll be implementing the rest of the feedback regarding UI/UX as well as implementing a solution for the filtering and sorting.

In the mean time, it would be helpful if you would do review and finalise any feedback of the latest implementation ([see OHLOOM here](https://zen-stonebraker-a93ddf.netlify.app/detail/Q438), verify some other items that aren't populated with as much data)

** Download Bundle button**
With repositories hosted on Appropedia, I can't seem to find any download link to generate for the 'Download Bundle' button. Should this button appear on appropedia imported items?

**Comment by jdittrich** [comment]
>  Suggestion: Can we gray out the Download Bundle button for projects with no downloadable files available?

Or just don't have it, as the user can't change anything about this

**Comment by ckawohl-wmde** [comment]
This hasn't been touched in months. I will close it.
