### ISSUE TITLE
Set up continuous deployment & testing pipeline

### ISSUE THREAD

**Issue by ckawohl-wmde** [wmde/LOSH-Frontend#7]

**Comment by botoxparty** [comment]
Currently, the infrastructure required to continuously deploy is not in place and releases need to be triggered manually by contacting @aisbergg when there is a successful build on the `main` branch that you would like deployed 

@aisbergg could you add any further details here about your proposed strategy

**Comment by ckawohl-wmde** [comment]
@aisbergg Would be great to have your input on a potential strategy. Otherwise we would close the issue.

**Comment by aisbergg** [comment]
I do not plan to set up a CD pipeline. I continue to deploy new versions manually when required.

**Comment by ckawohl-wmde** [comment]
Thanks for the feedback, @aisbergg!
