### ISSUE TITLE
Server cannot be build using the production packages

### ISSUE THREAD

**Issue by aisbergg** [wmde/LOSH-Frontend#74]
**Describe the bug**
The server cannot be build using only the _production_ packages, because it misses the `typescript` package. It can be added manually: `yarn server add typescript@^4.4.4`

**To Reproduce**

1. Install server build-packages: `yarn server install --production`
2. Execute build: `yarn server build`

**Additional context**

The error message:

```plaintext
yarn run v1.22.5
$ yarn workspace server build
$ tsc -p . && ncp src dist
/bin/sh: tsc: not found
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 127
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.5/lib/cli.js build
Directory: /tmp/losh-backend-src/packages/server
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 127.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by botoxparty** [comment]
Added to package.json for the server 👍

**Comment by aisbergg** [comment]
In the current version it still won't build without modifications. I guess you have to update the lock file too.

Works for me: `yarn upgrade typescript@^4.4.4`
