### ISSUE TITLE
Download Results of Search

### ISSUE THREAD

**Issue by jdittrich** [wmde/LOSH-Frontend#78]
The search results should be downloadable. 

Interface: 
![grafik](https://user-images.githubusercontent.com/3416487/142223880-bdfaa1b8-e112-46ee-869a-07546ed26b9f.png)

Requirements: 
* Download all search results, not only the ones on the current page
* CSV-Format, I guess?

**Comment by botoxparty** [comment]
Results can be downloaded as a CSV file 👍
