### ISSUE TITLE
multi-project list per page e.g. 100/page does not work

### ISSUE THREAD

**Issue by timmwille** [wmde/LOSH-Frontend#82]
**Describe the bug**
100/page function (also in general multi-projects list above 10/page) not working 

**To Reproduce**

1. Go to startpage
2. Click on dropdown 10/page and chose e.g. 100/page
3. → nothing happens

**Expected behavior**
When going for a rough unspecific overview of as many projects listed as possible one would like to see more then 10 per page at once → so the missing filter is a little critical as clicking trough the pages is a lot more work. → it also does not work when having a license filter activated

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8081055/144114931-a2985d9b-2455-41a9-9710-1f779f3042f8.png)

**Desktop (please complete the following information):**

- OS: Manjaro Linux
- Browser: Firefox
- Version: 94.0.1

**Additional context**
is it possible to at least view/download the full list? (especially relevant to research)

**Comment by moedn** [comment]
Can replicate this error; in fact, none of the options (20…100 / page) work for me

- OS: Fedora 34
- Browser: Brave v1.32.113

**Comment by moedn** [comment]
> is it possible to at least view/download the full list? (especially relevant to research)

@timmwille see the `download results` button in the bottom right corner of your screenshot :)
